# Generated by Django 4.0.1 on 2022-02-10 01:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('pronouns', models.CharField(blank=True, max_length=50, null=True)),
                ('phonetics', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=127)),
                ('email', models.CharField(max_length=125)),
                ('fav_color', models.CharField(blank=True, max_length=50, null=True)),
                ('fav_color_to_wear', models.CharField(blank=True, max_length=50, null=True)),
                ('fav_food_snack', models.TextField(blank=True, null=True)),
                ('shoe_size', models.FloatField(blank=True, null=True)),
                ('clothes_top_size', models.CharField(blank=True, max_length=50, null=True)),
                ('clothes_bottom_size', models.CharField(blank=True, max_length=50, null=True)),
                ('dont_want_list', models.TextField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('claimed', models.BooleanField(default=False)),
                ('item_link', models.URLField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_image', models.URLField(blank=True, null=True)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='items_list', to='base.WishList')),
            ],
        ),
    ]
