# Generated by Django 4.0.1 on 2022-01-27 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('pronouns', models.CharField(max_length=50)),
                ('fav_color', models.CharField(blank=True, max_length=50, null=True)),
                ('fav_color_to_wear', models.CharField(blank=True, max_length=50, null=True)),
                ('fav_food_snack', models.TextField(blank=True, null=True)),
                ('shoe_size', models.PositiveIntegerField(blank=True, null=True)),
                ('clothes_top_size', models.CharField(blank=True, max_length=50, null=True)),
                ('clothes_bottom_size', models.CharField(blank=True, max_length=50, null=True)),
                ('dont_want_list', models.TextField(blank=True, null=True)),
                ('pinterest_link', models.URLField(blank=True, null=True)),
                ('amazon_link', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
