# Generated by Django 4.0.1 on 2022-01-28 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='shoe_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
