# Generated by Django 4.0.1 on 2022-01-28 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userprofile_pronouns_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='wishlists',
            new_name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('claimed', models.BooleanField(default=False)),
                ('item_link', models.URLField(blank=True, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='base.wishlist')),
            ],
        ),
    ]
