# Generated by Django 4.0.1 on 2022-01-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_wishlists_wishlist_user_wishlist_created_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='wishlist',
        ),
        migrations.AddField(
            model_name='item',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='items_list', to='base.WishList'),
        ),
    ]
