# Generated by Django 4.0.1 on 2022-02-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_item_wishlist_item_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phonetics',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
